package mcp

// install.go provides pure helper functions for idempotent install and clean
// uninstall of Junction's MCP wiring:
//
//   - WriteMCPEntry  — keyed mutation of .mcp.json (mcpServers.junction)
//   - RemoveMCPEntry — surgical removal of exactly mcpServers.junction
//   - WriteSkill     — marker-bounded write/replace of SKILL.md
//   - RemoveSkill    — marker-bounded excision; deletes file when empty after
//
// All functions accept explicit file-system paths so they are testable without
// touching real project directories.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// mcpMarkerStart / mcpMarkerEnd are the HTML-comment markers that bound the
// Junction-owned section inside SKILL.md. They follow the nexus
// <!-- eidolon:<name> start/end --> convention.
const (
	mcpMarkerStart = "<!-- junction:mcp start -->"
	mcpMarkerEnd   = "<!-- junction:mcp end -->"
)

// junctionServerKey is the key written under mcpServers in .mcp.json.
const junctionServerKey = "junction"

// MCPServerConfig is the shape written under mcpServers.junction in .mcp.json.
// Keeping it typed ensures the marshalled form is deterministic — no stray
// keys, alphabetically sorted by encoding/json.
type MCPServerConfig struct {
	Args    []string `json:"args"`
	Command string   `json:"command"`
	Type    string   `json:"type"`
}

// defaultServerConfig is the canonical config written by junction mcp install.
// args/command/type are sorted alphabetically by encoding/json when marshalled.
var defaultServerConfig = MCPServerConfig{
	Args:    []string{"mcp", "serve"},
	Command: "junction",
	Type:    "stdio",
}

// DefaultServerConfig returns a copy of the canonical MCPServerConfig that
// WriteMCPEntry writes under mcpServers.junction.
func DefaultServerConfig() MCPServerConfig {
	return defaultServerConfig
}

// skillContent is the SKILL.md body that is written between the markers.
// It describes the four MCP tools advertised by junction mcp serve.
const skillContent = `<!-- junction:mcp start -->
# Junction MCP Skill

This skill is auto-generated by ` + "`junction mcp install --with-skill`" + `.

## What is Junction?

Junction is the ECL (Eidolons Communication Layer) production harness. It
orchestrates multi-Eidolon hand-offs via envelope-based dispatch.

## Available MCP Tools

### harness.plan_from_prompt

Reserved for future use. In the two-phase Junction model the host LLM (Claude
Code) is the planner; Junction executes the plan. For now, construct a
plan.json manually (see the Junction spec §7.5) and call harness.run.

**Input:** ` + "`prompt`" + ` (string) — natural-language task description.

### harness.run

Execute a Junction plan. Reads plan.json at plan_path, dispatches each step
via the appropriate executor, and returns the thread_id and trace_root.

**Input:** ` + "`plan_path`" + ` (string) — absolute or relative path to plan.json.

### harness.verify

Verify an ECL envelope against L1 (schema), L2 (integrity), L3 (edge), and
L4 (performative) checks.

**Input:** ` + "`envelope_path`" + ` (string) — path to the ECL envelope file.

**Output:** ` + "`ok`" + ` (bool) + ` + "`errors`" + ` (list).

### harness.inject

STUB (v0.1). Human-in-the-loop envelope injection (§5.7/§6.5). Not
implemented yet — returns ` + "`ok: false`" + ` with a descriptive error.

**Input:** ` + "`thread_id`" + ` (string), ` + "`envelope`" + ` (object).

## Usage

The server is launched automatically by Claude Code as a stdio subprocess
via the ` + "`.mcp.json`" + ` entry written by ` + "`junction mcp install`" + `.

To remove this wiring: ` + "`junction mcp uninstall`" + `.
<!-- junction:mcp end -->
`

// ─── .mcp.json helpers ───────────────────────────────────────────────────────

// WriteMCPEntry reads mcpJSONPath (creating it if absent), sets
// mcpServers.junction to the canonical server config, and writes the result
// back atomically. The operation is idempotent: calling it twice with the same
// input produces byte-identical output.
//
// Other keys in mcpServers (and any other top-level keys) are preserved.
func WriteMCPEntry(mcpJSONPath string, serverConfig MCPServerConfig) error {
	m, err := readOrCreateMCPJSON(mcpJSONPath)
	if err != nil {
		return fmt.Errorf("WriteMCPEntry: reading %s: %w", mcpJSONPath, err)
	}

	// Ensure mcpServers is a map[string]interface{}.
	servers, err := ensureMCPServers(m)
	if err != nil {
		return fmt.Errorf("WriteMCPEntry: %w", err)
	}

	// Set the junction entry. MCPServerConfig fields are sorted alphabetically
	// by encoding/json (args, command, type) — deterministic output guaranteed.
	servers[junctionServerKey] = serverConfig
	m["mcpServers"] = servers

	return writeMCPJSON(mcpJSONPath, m)
}

// RemoveMCPEntry reads mcpJSONPath, deletes the mcpServers.junction key, and
// writes the result back. If mcpServers becomes empty the key is left as {}
// (other tools may re-populate it). If the file does not exist, RemoveMCPEntry
// is a no-op.
func RemoveMCPEntry(mcpJSONPath string) error {
	if _, err := os.Stat(mcpJSONPath); os.IsNotExist(err) {
		return nil
	}

	m, err := readOrCreateMCPJSON(mcpJSONPath)
	if err != nil {
		return fmt.Errorf("RemoveMCPEntry: reading %s: %w", mcpJSONPath, err)
	}

	servers, err := ensureMCPServers(m)
	if err != nil {
		// If mcpServers isn't a map at all there is nothing to remove.
		return nil
	}

	delete(servers, junctionServerKey)
	m["mcpServers"] = servers

	return writeMCPJSON(mcpJSONPath, m)
}

// readOrCreateMCPJSON returns the parsed top-level map from the JSON file at
// path. If the file does not exist an empty map is returned (no error).
func readOrCreateMCPJSON(path string) (map[string]interface{}, error) {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return map[string]interface{}{}, nil
	}
	if err != nil {
		return nil, err
	}
	// Handle empty file.
	if len(strings.TrimSpace(string(raw))) == 0 {
		return map[string]interface{}{}, nil
	}
	var m map[string]interface{}
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("parsing JSON: %w", err)
	}
	return m, nil
}

// ensureMCPServers returns the mcpServers sub-map from m, creating it if
// absent. Returns an error only when the existing value is not a JSON object.
func ensureMCPServers(m map[string]interface{}) (map[string]interface{}, error) {
	raw, ok := m["mcpServers"]
	if !ok || raw == nil {
		servers := map[string]interface{}{}
		return servers, nil
	}
	servers, ok := raw.(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("mcpServers is not an object (got %T)", raw)
	}
	return servers, nil
}

// writeMCPJSON marshals m to indented JSON and writes it atomically to path.
// encoding/json sorts map keys alphabetically, so the output is byte-stable
// for the same logical value.
func writeMCPJSON(path string, m map[string]interface{}) error {
	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return fmt.Errorf("marshalling JSON: %w", err)
	}
	// Append a trailing newline for POSIX compliance.
	data = append(data, '\n')

	// Atomic write: temp file in the same directory → rename.
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dir, err)
	}

	tmp, err := os.CreateTemp(dir, ".mcp.json.tmp")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("writing temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("closing temp file: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("renaming temp file: %w", err)
	}
	return nil
}

// ─── SKILL.md helpers ────────────────────────────────────────────────────────

// WriteSkill writes a marker-bounded SKILL.md to skillPath using the provided
// content (which must already include the marker lines). The operation is
// idempotent:
//
//   - If the file does not exist, it is created with content as its full body.
//   - If the file exists and already contains the markers, the marker block is
//     replaced in place.
//   - If the file exists but lacks the markers, the marker block is appended
//     (preceded by a blank line).
func WriteSkill(skillPath string, content string) error {
	if err := os.MkdirAll(filepath.Dir(skillPath), 0o755); err != nil {
		return fmt.Errorf("WriteSkill: creating directory: %w", err)
	}

	existing, err := os.ReadFile(skillPath)
	if os.IsNotExist(err) {
		// Fresh create.
		return os.WriteFile(skillPath, []byte(content), 0o644)
	}
	if err != nil {
		return fmt.Errorf("WriteSkill: reading %s: %w", skillPath, err)
	}

	existingStr := string(existing)
	if containsMarkers(existingStr) {
		// Replace the existing marker block.
		replaced := replaceMarkerBlock(existingStr, content)
		return os.WriteFile(skillPath, []byte(replaced), 0o644)
	}

	// Append: ensure there is a blank line before the marker block.
	appended := strings.TrimRight(existingStr, "\n") + "\n\n" + content
	return os.WriteFile(skillPath, []byte(appended), 0o644)
}

// RemoveSkill excises the marker-bounded section from skillPath. If the file
// becomes empty (all whitespace) after removal it is deleted. If the file does
// not exist, RemoveSkill is a no-op.
func RemoveSkill(skillPath string) error {
	existing, err := os.ReadFile(skillPath)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("RemoveSkill: reading %s: %w", skillPath, err)
	}

	existingStr := string(existing)
	if !containsMarkers(existingStr) {
		// Nothing to remove.
		return nil
	}

	excised := exciseMarkerBlock(existingStr)
	if strings.TrimSpace(excised) == "" {
		return os.Remove(skillPath)
	}
	return os.WriteFile(skillPath, []byte(excised), 0o644)
}

// SkillContent returns the canonical SKILL.md body (marker-bounded) that
// WriteSkill writes. Exposed for use by the cmd layer and tests.
func SkillContent() string {
	return skillContent
}

// ─── marker helpers ──────────────────────────────────────────────────────────

// markerBlockRE matches the marker start, everything in between (including
// newlines), and the marker end, plus one optional trailing newline.
var markerBlockRE = regexp.MustCompile(
	regexp.QuoteMeta(mcpMarkerStart) +
		`[\s\S]*?` +
		regexp.QuoteMeta(mcpMarkerEnd) +
		`\n?`,
)

// containsMarkers returns true when both marker strings appear in s.
func containsMarkers(s string) bool {
	return strings.Contains(s, mcpMarkerStart) && strings.Contains(s, mcpMarkerEnd)
}

// replaceMarkerBlock replaces the existing marker block in s with newBlock.
func replaceMarkerBlock(s, newBlock string) string {
	return markerBlockRE.ReplaceAllLiteralString(s, newBlock)
}

// exciseMarkerBlock removes the marker block from s and trims any resulting
// double blank lines at the excision point.
func exciseMarkerBlock(s string) string {
	result := markerBlockRE.ReplaceAllLiteralString(s, "")
	// Collapse triple+ newlines left by removing the block (e.g. preceding
	// blank line + blank line from removal).
	tripleNL := regexp.MustCompile(`\n{3,}`)
	result = tripleNL.ReplaceAllString(result, "\n\n")
	return result
}
