name: examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  single-eidolon-happy-path:
    name: example / single-eidolon-happy-path
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run example
        run: bash examples/single-eidolon-happy-path/run.sh

  trance-chain:
    name: example / trance-chain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run example
        run: bash examples/trance-chain/run.sh
